---

organizr:
  name: "{{ global.organizr.name }}"
  image: lsiocommunity/organizr
  port:
    http: 8083
  config:
    directory: "{{ base_folder }}/organizr"
    auth:
      type: both
      backend: ldap
      domain: home
      host: "ldap://10.0.9.10:389"
    database: /config/www/
    user_home: /config/www/users/
    # monday
    calendarStart: 1
    couchHomeAuth: "false"
    nzbgetHomeAuth: "false"
    sonarrHomeAuth: "false"