---

organizr:
  name: organizr
  image: lsiocommunity/organizr
  port:
    http: 8083
  config:
    directory: "{{ base_folder }}/organizr"
    auth:
      backend: ldap
      domain: home
      host: "ldap://10.0.9.10:389"
