---

- name: Delete NZB Hydra configuration (for fresh config)
  file:
    dest: "{{ nzbhydra.config.directory }}/hydra/settings.cfg"
    state: absent

- name: Copy NZB Hydra configuration
  template:
    src: settings.cfg.j2
    dest: "{{ nzbhydra.config.directory }}/hydra/settings.cfg"

- name: Pull NZB Hydra image
  docker_container:
    name: "{{ nzbhydra.name }}"
    image: "{{ nzbhydra.image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker.network }}"
    published_ports:
      - "{{nzbhydra.port}}:{{nzbhydra.port}}"
    volumes:
      - "{{ nzbhydra.config.directory }}:/config"
      - "{{ folders.watch }}:/watch"
    env:
      PUID: "{{ user.uid }}"
      PGID: "{{ user.gid }}"
      TZ: "{{ timezone }}"
