---

- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - raw: which /usr/bin/python || which /usr/bin/python3
      register: py_interpreter
      changed_when: py_interpreter.stdout != ""
    - set_fact:
        ansible_python_interpreter: "{{ py_interpreter.stdout }}"
    - name: Gathering Facts
      setup: #aka gather_facts

  roles:
    - docker

  # vars_files:
  #   - vars/services.yml
  #   - vars/httpauthusers.yml

  # roles:
    # - ubuntu-setup
    # - network-shares
    # - docker
    # - docker-network
    # - nzbget-docker
    # - transmission-docker
    # - nzbhydra2-docker
    # - sonarr-docker
    # - couchpotato-docker
    # - jdownloader-docker
    # - organizr-docker
    # - portainer-docker
    # - traefik-docker
    # - backstroke
    # - watchtower-docker
    # - docker-backup
    # - datadog-docker
    # - logzio-docker

    # Testing
    # - radarr-docker

    # Old
    # - freenas-permissions
    # - centos-setup
    # - muximux-docker
    # - docker-gen
    # - nzbhydra-docker
    # - nginx-docker

  post_tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required
    - name: Restart if reboot is required
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: true
      become: true
      when: reboot_required.stat.exists == true

## Save this for Packer
# Just for setting IP addresses
# - hosts: new-machine
#
#   roles:
#     - static-ip
