---

- hosts: usenet, vagrant

  vars_files:
    - vars/services.yml

  roles:
    # - ubuntu-setup
    # - network-shares
    # - docker
    # - docker-network
    - nzbget-docker
    # - transmission-docker
    # - nzbhydra-docker
    # - sonarr-docker
    # - couchpotato-docker
    # - organizr-docker
    # - portainer-docker
    # - nginx-docker
    # - letsencrypt-docker
    # - backstroke
    # - watchtower-docker

    # Testing
    # - radarr-docker

    # Old
    # - freenas-permissions
    # - centos-setup
    # - muximux-docker

## Save this for Packer
# Just for setting IP addresses
# - hosts: new-machine
#
#   roles:
#     - static-ip
