---

- hosts: usenet

  vars_files:
    - vars/common.yml
    - vars/couchpotato.yml
    - vars/freenas.yml
    - vars/letsencrypt.yml
    - vars/muximux.yml
    - vars/nginx.yml
    - vars/nzbget.yml
    - vars/nzbhydra.yml
    - vars/services.yml
    - vars/radarr.yml
    - vars/sonarr.yml
    - vars/transmission.yml

  roles:
    - ubuntu-setup
    - network-shares
    - docker
    - docker-network
    - nzbget-docker
    - transmission-docker
    - nzbhydra-docker
    - sonarr-docker
    - couchpotato-docker
    - muximux-docker
    - nginx-docker
    - letsencrypt-docker
    # - freenas-permissions
    # - centos-setup
    # - radarr-docker

# Just for setting IP addresses

- hosts: new-machine

  vars_files:
    - vars/common.yml

  roles:
    - static-ip
