---

- hosts: usenet

  vars_files:
    - vars/services.yml

  roles:
    - ubuntu-setup
    - network-shares
    - docker
    - docker-network
    - nzbget-docker
    - transmission-docker
    - nzbhydra-docker
    - sonarr-docker
    - radarr-docker
    - organizr-docker
    - nginx-docker
    - letsencrypt-docker
    # - freenas-permissions
    # - centos-setup
    # - couchpotato-docker
    # - muximux-docker

# Just for setting IP addresses
- hosts: new-machine

  roles:
    - static-ip
