---

- name: Pull Portainer image
  docker_container:
    name: "{{ portainer.name }}"
    image: "{{ portainer.image }}"
    state: started
    recreate: yes
    restart_policy: unless-stopped
    command: --no-auth
    networks:
      - name: "{{ docker.network }}"
    published_ports:
      - "{{ portainer.port.http }}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ portainer.config.directory }}:/data"
    labels:
      traefik.frontend.rule: "Host:{{ portainer.name }}.{{ global.domain }}"
