---

- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install open-vm-tools
  apt:
    name: open-vm-tools
    state: latest
    cache_valid_time: 3600
  become: true

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  become: true

- name: Wait for server to come back
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      state=started
      delay=5
      timeout=30
