---

services:
# -
#   name: Muximux
#   location: /
#   # Muximux is running on port 80 on the host but exposed through 8080 on the host
#   proxy_pass: "http://{{ muximux.name }}.{{ docker.network }}"
-
  name: Organizr
  location: /
  proxy_pass: "http://{{ organizr.name }}.{{ docker.network }}"
  include:
    - "{{ nginx.proxy.file }}"
-
  name: NZBGet
  location: /nzbget/
  icon:  "muximux-download"
  color: "#ffffff"
  proxy_pass: "http://{{ nzbget.name }}.{{ docker.network }}:{{ nzbget.port.http}}"
-
  name: Sonarr
  location: /sonarr
  icon:  "muximux-sonarr"
  color: "#35c5f4"
  proxy_pass: "http://{{ sonarr.name }}.{{ docker.network }}:{{ sonarr.port.http }}{{ sonarr.config.urlbase }}"
  include:
    - "{{ nginx.proxy.file }}"
-
  name: Radarr
  location: /radarr
  icon:  "muximux-movie_creation"
  color: "#ff0000"
  proxy_pass: "http://{{ radarr.name }}.{{ docker.network }}:{{ radarr.port.http }}{{ radarr.config.urlbase }}"
  include:
    - "{{ nginx.proxy.file }}"
-

  name: "NZB Hydra"
  location: /nzbhydra
  icon:  "muximux-nzbhydra"
  color: "#108f34"
  proxy_pass: "http://{{ nzbhydra.name }}.{{ docker.network}}:{{ nzbhydra.port }}{{ nzbhydra.config.main.urlBase }}"
-
  name: Transmission
  location: /transmission
  icon:  "muximux-transmission"
  color: "#000000"
  proxy_pass: "http://{{ transmission.name }}.{{ docker.network }}:{{ transmission.port.web }}"
# -
#   name: Radarr
#   location: /radarr
#   icon:  "muximux-movie_creation"
#   color: "#ff9900"
#   proxy_pass: "http://{{ radarr.name }}.{{ docker.network }}:{{ radarr.port.http }}{{ radarr.config.urlbase }}"
#   include:
#     - "{{ nginx.proxy.file }}"
