---

services:
# -
#   name: Muximux
#   location: /
#   # Muximux is running on port 80 on the host but exposed through 8080 on the host
#   proxy_pass: "http://{{ muximux.name }}.{{ docker.network }}"
-
  name: Organizr
  location: /
  proxy_pass: "http://{{ organizr.name }}.{{ docker.network }}"
-
  name: NZBGet
  location: /nzbget/
  proxy_pass: "http://{{ nzbget.name }}.{{ docker.network }}:{{ nzbget.port.http}}"
-
  name: Sonarr
  location: /sonarr
  proxy_pass: "http://{{ sonarr.name }}.{{ docker.network }}:{{ sonarr.port.http }}{{ sonarr.config.urlbase }}"
  include:
    - "include {{ nginx.proxy.file }}"
-
  name: "NZB Hydra"
  location: /nzbhydra
  proxy_pass: "http://{{ nzbhydra.name }}.{{ docker.network}}:{{ nzbhydra.port }}{{ nzbhydra.config.main.urlBase }}"
-
  name: Transmission
  location: /transmission
  proxy_pass: "http://{{ transmission.name }}.{{ docker.network }}:{{ transmission.port.web }}"
-
  name: CouchPotato
  location: /couchpotato
  proxy_pass: "http://{{ couchpotato.name }}.{{ docker.network }}:{{ couchpotato.port.http }}{{ couchpotato.config.core.urlbase }}"
# -
#   name: Radarr
#   location: /radarr
#   icon:  "muximux-movie_creation"
#   color: "#ff9900"
#   proxy_pass: "http://{{ radarr.name }}.{{ docker.network }}:{{ radarr.port.http }}{{ radarr.config.urlbase }}"
#   include:
#     - "{{ nginx.proxy.file }}"
# -
#   name: Portainer
#   location: /portainer/
#   proxy_pass: "http://{{ portainer.name }}.{{ docker.network }}:{{ portainer.port.http }}"
#   include:
#     - 'proxy_http_version 1.1'
#     - 'proxy_set_header Connection ""'
# -
#   name: Portainer Web Socket
#   location: /portainer/api/websocket/
#   proxy_pass: "http://{{ portainer.name }}.{{ docker.network }}/api/websocket/:{{ portainer.port.http }}"
#   include:
#     - 'proxy_set_header Upgrade $http_upgrade'
#     - 'proxy_set_header Connection "upgrade"'
#     - 'proxy_http_version 1.1'
