---

- name: Delete Sonarr configuration file (for fresh config)
  file:
    state: absent
    path: "{{ sonarr.config.directory }}/config.xml"

- name: Pull Sonarr image
  docker_container:
    name: "{{ sonarr.name }}"
    image: "{{ sonarr.image }}"
    state: started
    recreate: yes
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker.network }}"
    published_ports:
      - "{{ sonarr.port.http }}:{{ sonarr.port.http }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ sonarr.config.directory }}:/config"
      - "{{ folders.tv }}:/tv"
      - "{{ folders.downloads }}:/downloads"
    env:
      PUID: "{{ user.uid }}"
      PGID: "{{ user.gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.frontend.rule: "Host:{{ sonarr.name }}.{{ global.domain }}"
      traefik.frontend.auth.basic: "{{ httpauthusers.calvin.name }}:{{ httpauthusers.calvin.password }},{{ httpauthusers.tammy.name }}:{{ httpauthusers.tammy.password }}"

- name: Wait until the Sonarr to start successfully
  wait_for:
    timeout: 20
  delegate_to: localhost

- name: Stop Sonarr to change configuration
  docker_container:
    name: "{{ sonarr.name }}"
    state: stopped

# Some require colons to differentitate from '-enabled' for regex
- name: Edit Sonarr configuration
  lineinfile:
    dest: "{{ sonarr.config.directory }}/config.xml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs:
  with_items:
  - regexp: '<Port>'
    line: '<Port>{{ sonarr.port.http }}</Port>'
  - regexp: '<UrlBase>'
    line: '<UrlBase>{{ sonarr.config.urlbase }}</UrlBase>'
  - regexp: '<SslPort>'
    line: '<SslPort>{{ sonarr.port.https }}</SslPort>'
  - regexp: '<ApiKey>'
    line: '<ApiKey>{{ sonarr.config.apikey }}</ApiKey>'

- name: Restart Sonarr
  docker_container:
    name: "{{ sonarr.name }}"
    state: started
    restart: yes
