---

- name: Create Sonarr config folder
  file:
    path: "{{ sonarr.config.directory }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0771"
  become: true

- name: Copy configuration file
  template:
    src: config.xml.j2
    dest: "{{ sonarr.config.directory }}/config.xml"

- name: Pull Sonarr image
  docker_container:
    name: "{{ sonarr.name }}"
    image: "{{ sonarr.image }}"
    state: started
    recreate: yes
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker.network }}"
    published_ports:
      - "{{ sonarr.port.http }}:{{ sonarr.port.http }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ sonarr.config.directory }}:/config"
      - "{{ folders.tv }}:/tv"
      - "{{ folders.downloads }}:/downloads"
    env:
      PUID: "{{ user.uid }}"
      PGID: "{{ user.gid }}"
      TZ: "{{ timezone }}"
