---

- name: Add certbot repo
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install certbot
  apt:
    name: certbot
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
