---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Add user to Docker group
  user:
    name: "{{user.name}}"
    groups: docker
    append: yes
  become: true

- name: Start docker after network shares are mounted
  lineinfile:
    path: /lib/systemd/system/docker.socket
    state: present
    insertafter: '^\[Unit\]$'
    line: "After={{ nfs_mount.unit_file }}.mount"
  become: true

# Required for some Ansible modules
- name: Install docker-py
  pip:
    name: docker-py
  become: true
