---

- name: Create Organizr config folder
  file:
    path: "{{ organizr.config.directory }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0771"
  become: true

- name: Copy configuration file
  template:
    src: config.php.j2
    dest: "{{ organizr.config.directory }}/www/Dashboard/config/config.php"

- name: Pull Organizr image
  docker_container:
    name: "{{ organizr.name }}"
    image: "{{ organizr.image }}"
    state: started
    recreate: yes
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker.network }}"
    published_ports:
      - "{{ organizr.port.http }}:80"
    volumes:
      - "{{ organizr.config.directory }}:/config"
    env:
      PUID: "{{ user.uid }}"
      PGID: "{{ user.gid }}"
