---

sonarr:
  name: "{{ global.sonarr.name }}"
  image: linuxserver/sonarr
  port:
    http: "{{ global.sonarr.port.http }}"
    https: 9898
  config:
    directory: "{{ base_folder }}/sonarr"
    urlbase: "{{ global.sonarr.config.urlbase }}"
    apikey: "{{ global.sonarr.config.apikey }}"
