---

couchpotato:
  name: "{{ global.couchpotato.name }}"
  image: linuxserver/couchpotato
  port:
    http: "{{ global.couchpotato.port.http }}"
    https: 5151
  config:
    directory: "{{ base_folder }}/couchpotato"
    core:
      apikey: "{{ global.couchpotato.config.core.apikey }}"
      dark_theme: 1
      launch_browser: 0
      dereferrer: ""
      urlbase: "{{ global.couchpotato.config.core.urlbase }}"
      show_wizard: 0
    manage:
      library_refresh_interval: 24
      cleanup: 0
      enabled: 1
      library: /movies/
    renamer:
      file_name: <thename><cd>.<quality>.<group>.<ext>
      nfo_name: <filename>.<ext>
      from: /downloads/Movies/
      to: /movies/
      cleanup: 1
      enabled: 1
      unrar: 1
    subtitle:
      languages: en
      enabled: 1
    trailer:
      enabled: 1
    blackhole:
      enabled: 0
    nzbget:
      enabled: 1
    transmission:
      enabled: 1
    pushbullet:
      enabled: 1
    newznab:
      use: 1
      extra_score: ""
      custom_tag: ""
    kickasstorrents:
      enabled: 0
    torrentz:
      enabled: 0
    searcher:
      preferred_method: nzb
    imdb:
      chart_display_top250: 1
      chart_display_theater: 1
    moviesearcher:
      cron_hour: 8
      cron_minute: 15
